name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: dkp-pacman -Syu --noconfirm libnx switch-tools libpng zlib freetype
    
    - name: Build
      run: |
        export DEVKITPRO=/opt/devkitpro
        export DEVKITA64=${DEVKITPRO}/devkitA64
        make -j$(nproc)
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: come-pad-ovl
        path: |
          *.ovl
          *.nro
